//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("DiemThiDHModel", "FK_Nganh_Truong", "Truong", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(XemDiemThiService.DAL.Truong), "Nganh", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(XemDiemThiService.DAL.Nganh), true)]
[assembly: EdmRelationshipAttribute("DiemThiDHModel", "FK_ThiSinh_Nganh", "Nganh", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(XemDiemThiService.DAL.Nganh), "ThiSinh", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(XemDiemThiService.DAL.ThiSinh), true)]

#endregion

namespace XemDiemThiService.DAL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DiemThiDHEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DiemThiDHEntities object using the connection string found in the 'DiemThiDHEntities' section of the application configuration file.
        /// </summary>
        public DiemThiDHEntities() : base("name=DiemThiDHEntities", "DiemThiDHEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DiemThiDHEntities object.
        /// </summary>
        public DiemThiDHEntities(string connectionString) : base(connectionString, "DiemThiDHEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DiemThiDHEntities object.
        /// </summary>
        public DiemThiDHEntities(EntityConnection connection) : base(connection, "DiemThiDHEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Nganh> Nganhs
        {
            get
            {
                if ((_Nganhs == null))
                {
                    _Nganhs = base.CreateObjectSet<Nganh>("Nganhs");
                }
                return _Nganhs;
            }
        }
        private ObjectSet<Nganh> _Nganhs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ThiSinh> ThiSinhs
        {
            get
            {
                if ((_ThiSinhs == null))
                {
                    _ThiSinhs = base.CreateObjectSet<ThiSinh>("ThiSinhs");
                }
                return _ThiSinhs;
            }
        }
        private ObjectSet<ThiSinh> _ThiSinhs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Truong> Truongs
        {
            get
            {
                if ((_Truongs == null))
                {
                    _Truongs = base.CreateObjectSet<Truong>("Truongs");
                }
                return _Truongs;
            }
        }
        private ObjectSet<Truong> _Truongs;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Nganhs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNganhs(Nganh nganh)
        {
            base.AddObject("Nganhs", nganh);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ThiSinhs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToThiSinhs(ThiSinh thiSinh)
        {
            base.AddObject("ThiSinhs", thiSinh);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Truongs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTruongs(Truong truong)
        {
            base.AddObject("Truongs", truong);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DiemThiDHModel", Name="Nganh")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Nganh : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Nganh object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="maTruong">Initial value of the MaTruong property.</param>
        /// <param name="tenNganh">Initial value of the TenNganh property.</param>
        public static Nganh CreateNganh(global::System.Int32 id, global::System.String maTruong, global::System.String tenNganh)
        {
            Nganh nganh = new Nganh();
            nganh.Id = id;
            nganh.MaTruong = maTruong;
            nganh.TenNganh = tenNganh;
            return nganh;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaTruong
        {
            get
            {
                return _MaTruong;
            }
            set
            {
                OnMaTruongChanging(value);
                ReportPropertyChanging("MaTruong");
                _MaTruong = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MaTruong");
                OnMaTruongChanged();
            }
        }
        private global::System.String _MaTruong;
        partial void OnMaTruongChanging(global::System.String value);
        partial void OnMaTruongChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TenNganh
        {
            get
            {
                return _TenNganh;
            }
            set
            {
                OnTenNganhChanging(value);
                ReportPropertyChanging("TenNganh");
                _TenNganh = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TenNganh");
                OnTenNganhChanged();
            }
        }
        private global::System.String _TenNganh;
        partial void OnTenNganhChanging(global::System.String value);
        partial void OnTenNganhChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DiemThiDHModel", "FK_Nganh_Truong", "Truong")]
        public Truong Truong
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Truong>("DiemThiDHModel.FK_Nganh_Truong", "Truong").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Truong>("DiemThiDHModel.FK_Nganh_Truong", "Truong").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Truong> TruongReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Truong>("DiemThiDHModel.FK_Nganh_Truong", "Truong");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Truong>("DiemThiDHModel.FK_Nganh_Truong", "Truong", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DiemThiDHModel", "FK_ThiSinh_Nganh", "ThiSinh")]
        public EntityCollection<ThiSinh> ThiSinhs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ThiSinh>("DiemThiDHModel.FK_ThiSinh_Nganh", "ThiSinh");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ThiSinh>("DiemThiDHModel.FK_ThiSinh_Nganh", "ThiSinh", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DiemThiDHModel", Name="ThiSinh")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ThiSinh : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ThiSinh object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="idNganh">Initial value of the IdNganh property.</param>
        /// <param name="hoTen">Initial value of the HoTen property.</param>
        /// <param name="ngaySinh">Initial value of the NgaySinh property.</param>
        /// <param name="queQuan">Initial value of the QueQuan property.</param>
        /// <param name="gioiTinh">Initial value of the GioiTinh property.</param>
        /// <param name="diem1">Initial value of the Diem1 property.</param>
        /// <param name="diem2">Initial value of the Diem2 property.</param>
        /// <param name="diem3">Initial value of the Diem3 property.</param>
        public static ThiSinh CreateThiSinh(global::System.Int32 id, global::System.Int32 idNganh, global::System.String hoTen, global::System.DateTime ngaySinh, global::System.String queQuan, global::System.Boolean gioiTinh, global::System.Double diem1, global::System.Double diem2, global::System.Double diem3)
        {
            ThiSinh thiSinh = new ThiSinh();
            thiSinh.Id = id;
            thiSinh.IdNganh = idNganh;
            thiSinh.HoTen = hoTen;
            thiSinh.NgaySinh = ngaySinh;
            thiSinh.QueQuan = queQuan;
            thiSinh.GioiTinh = gioiTinh;
            thiSinh.Diem1 = diem1;
            thiSinh.Diem2 = diem2;
            thiSinh.Diem3 = diem3;
            return thiSinh;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdNganh
        {
            get
            {
                return _IdNganh;
            }
            set
            {
                OnIdNganhChanging(value);
                ReportPropertyChanging("IdNganh");
                _IdNganh = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdNganh");
                OnIdNganhChanged();
            }
        }
        private global::System.Int32 _IdNganh;
        partial void OnIdNganhChanging(global::System.Int32 value);
        partial void OnIdNganhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HoTen
        {
            get
            {
                return _HoTen;
            }
            set
            {
                OnHoTenChanging(value);
                ReportPropertyChanging("HoTen");
                _HoTen = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("HoTen");
                OnHoTenChanged();
            }
        }
        private global::System.String _HoTen;
        partial void OnHoTenChanging(global::System.String value);
        partial void OnHoTenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime NgaySinh
        {
            get
            {
                return _NgaySinh;
            }
            set
            {
                OnNgaySinhChanging(value);
                ReportPropertyChanging("NgaySinh");
                _NgaySinh = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NgaySinh");
                OnNgaySinhChanged();
            }
        }
        private global::System.DateTime _NgaySinh;
        partial void OnNgaySinhChanging(global::System.DateTime value);
        partial void OnNgaySinhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String QueQuan
        {
            get
            {
                return _QueQuan;
            }
            set
            {
                OnQueQuanChanging(value);
                ReportPropertyChanging("QueQuan");
                _QueQuan = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("QueQuan");
                OnQueQuanChanged();
            }
        }
        private global::System.String _QueQuan;
        partial void OnQueQuanChanging(global::System.String value);
        partial void OnQueQuanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean GioiTinh
        {
            get
            {
                return _GioiTinh;
            }
            set
            {
                OnGioiTinhChanging(value);
                ReportPropertyChanging("GioiTinh");
                _GioiTinh = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GioiTinh");
                OnGioiTinhChanged();
            }
        }
        private global::System.Boolean _GioiTinh;
        partial void OnGioiTinhChanging(global::System.Boolean value);
        partial void OnGioiTinhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Diem1
        {
            get
            {
                return _Diem1;
            }
            set
            {
                OnDiem1Changing(value);
                ReportPropertyChanging("Diem1");
                _Diem1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Diem1");
                OnDiem1Changed();
            }
        }
        private global::System.Double _Diem1;
        partial void OnDiem1Changing(global::System.Double value);
        partial void OnDiem1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Diem2
        {
            get
            {
                return _Diem2;
            }
            set
            {
                OnDiem2Changing(value);
                ReportPropertyChanging("Diem2");
                _Diem2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Diem2");
                OnDiem2Changed();
            }
        }
        private global::System.Double _Diem2;
        partial void OnDiem2Changing(global::System.Double value);
        partial void OnDiem2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Diem3
        {
            get
            {
                return _Diem3;
            }
            set
            {
                OnDiem3Changing(value);
                ReportPropertyChanging("Diem3");
                _Diem3 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Diem3");
                OnDiem3Changed();
            }
        }
        private global::System.Double _Diem3;
        partial void OnDiem3Changing(global::System.Double value);
        partial void OnDiem3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SoBaoDanh
        {
            get
            {
                return _SoBaoDanh;
            }
            set
            {
                OnSoBaoDanhChanging(value);
                ReportPropertyChanging("SoBaoDanh");
                _SoBaoDanh = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SoBaoDanh");
                OnSoBaoDanhChanged();
            }
        }
        private global::System.String _SoBaoDanh;
        partial void OnSoBaoDanhChanging(global::System.String value);
        partial void OnSoBaoDanhChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DiemThiDHModel", "FK_ThiSinh_Nganh", "Nganh")]
        public Nganh Nganh
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Nganh>("DiemThiDHModel.FK_ThiSinh_Nganh", "Nganh").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Nganh>("DiemThiDHModel.FK_ThiSinh_Nganh", "Nganh").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Nganh> NganhReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Nganh>("DiemThiDHModel.FK_ThiSinh_Nganh", "Nganh");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Nganh>("DiemThiDHModel.FK_ThiSinh_Nganh", "Nganh", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DiemThiDHModel", Name="Truong")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Truong : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Truong object.
        /// </summary>
        /// <param name="maTruong">Initial value of the MaTruong property.</param>
        /// <param name="tenTruong">Initial value of the TenTruong property.</param>
        public static Truong CreateTruong(global::System.String maTruong, global::System.String tenTruong)
        {
            Truong truong = new Truong();
            truong.MaTruong = maTruong;
            truong.TenTruong = tenTruong;
            return truong;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MaTruong
        {
            get
            {
                return _MaTruong;
            }
            set
            {
                if (_MaTruong != value)
                {
                    OnMaTruongChanging(value);
                    ReportPropertyChanging("MaTruong");
                    _MaTruong = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MaTruong");
                    OnMaTruongChanged();
                }
            }
        }
        private global::System.String _MaTruong;
        partial void OnMaTruongChanging(global::System.String value);
        partial void OnMaTruongChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TenTruong
        {
            get
            {
                return _TenTruong;
            }
            set
            {
                OnTenTruongChanging(value);
                ReportPropertyChanging("TenTruong");
                _TenTruong = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TenTruong");
                OnTenTruongChanged();
            }
        }
        private global::System.String _TenTruong;
        partial void OnTenTruongChanging(global::System.String value);
        partial void OnTenTruongChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DiemThiDHModel", "FK_Nganh_Truong", "Nganh")]
        public EntityCollection<Nganh> Nganhs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Nganh>("DiemThiDHModel.FK_Nganh_Truong", "Nganh");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Nganh>("DiemThiDHModel.FK_Nganh_Truong", "Nganh", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
